language: python
python:
- 3.6
notifications:
  email: false
before_install:
- sudo apt-get update
- sudo apt-get -y install python-pip
- sudo pip install --upgrade pip
- pip install --upgrade pip
- pip install pycodestyle pylint
- pip install twine setuptools wheel
- pip install -r requirements.txt
jobs:
  include:
  - stage: linters
    name: pylint
    python: 3.6
    script: find . -name \*.py -exec pylint  {} +
  - script: find . -name \*.py -exec pycodestyle --ignore=W503 {} +
    name: pycodestyle
  - stage: tests
    name: tests
    python: 3.6
    script: python test.py
  - stage: upload
    name: upload
    python: 3.6
    script:
    - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload dist/* -u $PYPI_USER -p $PYPI_PASSWORD
stages:
- linters
- tests
- name: upload
  on:
    tags: true
env:
  global:
  - secure: PxuInbuPIZI79HMJHvWs4X3gP9NFkJ4qJcXLhfLTedB25fpkTRNq0ot2FmUuR06iNAwNk5wPLkaEqawHEBvsmO4HpPkqDExb0S7aFyGTbK1qr2R/r8qpLAkZoQhP6/654pCQaUy1oPTNDLFikNWKpc8JYQfoLU/04ygczyKK/5Gq0wAABQAL+TTk9rZGjo1LMOhqfV6s6c/L7MI0Niqm3In2L/4xIAfFRuzLdzz/tOyPXSUwKKZiUQLCqHOFr5NG06YCpkae0PAijN5t4xNwFkJjoznz64Xa8ab5x6Jv1oCzgqocvNSECtab1SqsQErlQL8ydNso+4VMgn4DfCdiSeFCWjsfAtN5vgKNOvpbxmYmUoQjNDr6d68PJW1fPJShZp8N3PbM4BAgb/NZRusCq+A+bOAPcUfI15blflMuhgp+TbFSZXuUy19iVe+jB4M86HV3oEoiQNH0j5haXI6NWgpSZA/K0Fkx2/lU3698Jq5lmMVhIK8L1l+KvwHASF6ps+S5KG+buk/TYwjLZDfXyyPLUBYjk99rKJU7XsKyZ/AT3yg5ILvEqh7dn8XNp/5hZyulh06JzTlkK09zuTaZx0qcjxCGb9T8pTsNOXJastngoFzJLrdrWs8BBoYO9tGo5nvKiBW0U3eIDgQ8qcJDI2m+OO2qeBudQxFyU0OAA3c=
  - secure: AF8vIC1kBxnnYBJ0UZBc3v71VYK4xHXDBgIkTC2AuBPHW6LN37/DLHTXouU60vY4bCtE/u/XyEs66DFPnV4kEsuYwTXBosW5GhDYhqUiy2hRm8NwjeAB312vZR58GO9SI3RtkY1rumTkl4WtpmKwjtmrbh5RQCVTcqp6VRBTi2RUWvD1tYIqwqz+UC37nDJDpzO6g+snzrGuJQtpIVt0AhJboyqGC5+8BWsgXd3hcTj11+SeLNLznmvAPWhEA0Fehk6wOH7xJsYDiV0ssDxkc56y1j3L8irFj+U5OdzQYYKKEN8ztrkDyuhgxOCnrJHt3LIfq7H0PskRXMtnaFAd4SbrzCCYzBQUE8oAHUS/NVZae8sha+ceaQTABYJ7cwgt9NcwpmcmbsvrQuuzoW5l77prRqXXktEwxlDHv8Fc/p41An91p5nnc1rtqDhwhGndZfopewt2VKfLhBhkivKvXeDkEfxUVCa1/qatKRCyc4kddsz4NkE1fF+22v8kus1q5nX6Hib2Dajtjqu1a/zgPTk9fmnV2g8SuwaFs11RuMH/rZmfdn4c80uWuWjPdTYaDaJ9vCYrauuyaj7Dhv0NYLkexjmPH1ztIk0TIR/3QCq35jF8RrlDpHeUf6Z5YLOHetvf5/Kln7Xxj/lNWNE++ze6egqcGDzHIDaGVYcA8is=
